language: python

python:
    - 3.7

bundler_args: --retry 3

before_install:
    - sudo apt-get update
    - sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
    - texhash

script:
    - source .envrc
    - travis_wait create-content -a
